name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        example: [examples/example1]
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: '3.x'
    - name: Install Platform IO
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio        

    - name: Run PlatformIO
      run: platformio ci --keep-build-dir  --lib="." --board=espresso_lite_v2
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}
